# Generated by Django 2.1.1 on 2018-10-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='picture_pic',
            new_name='profile_pic',
        ),
    ]
